import numpy as np
import json
from pathlib import Path
from PIL import Image
import io

# ── Load model once at startup ────────────────────────────────────────────────
BASE = Path(__file__).resolve().parent.parent.parent / "saved_models"

# Load class info + treatments
with open(BASE / "disease_classes.json", "r") as f:
    disease_info = json.load(f)

CLASS_NAMES = disease_info["classes"]
IMG_SIZE    = disease_info.get("img_size", 224)
TREATMENTS  = disease_info.get("treatments", {})

# Localized treatment text, generated by scripts/translate_disease_dataset.py
# (see that script's docstring for why this is a one-time offline script
# rather than live per-request translation). Loaded lazily and cached in
# memory — if the script hasn't been run yet, this file simply doesn't
# exist, and everything below falls back to the English TREATMENTS dict
# without erroring, so localization is purely additive/optional.
_I18N_TREATMENTS_PATH = BASE / "disease_classes_i18n.json"
_i18n_treatments_cache = None


def _load_i18n_treatments() -> dict:
    global _i18n_treatments_cache
    if _i18n_treatments_cache is not None:
        return _i18n_treatments_cache
    try:
        with open(_I18N_TREATMENTS_PATH, "r", encoding="utf-8") as f:
            _i18n_treatments_cache = json.load(f)
    except FileNotFoundError:
        _i18n_treatments_cache = {}
    return _i18n_treatments_cache

# Load Keras model
try:
    from tensorflow.keras.models import load_model
    disease_model = load_model(str(BASE / "disease_model.h5"))
    print(f"✅ Disease Detector model loaded — {len(CLASS_NAMES)} disease classes")
except Exception as e:
    disease_model = None
    print(f"⚠️ Disease model load failed: {e}")


def get_treatment(class_name: str, lang: str = "en") -> dict:
    """Get treatment info for a disease class name, in the given language
    if a translated version is available (see _load_i18n_treatments above)
    — otherwise falls back to the original English data."""
    if lang and lang != "en":
        localized = _load_i18n_treatments().get(lang, {})
        if class_name in localized:
            return localized[class_name]
        class_lower = class_name.lower()
        for key, treatment in localized.items():
            if key.lower() in class_lower or class_lower in key.lower():
                return treatment
        # No localized entry for this class/language — fall through to
        # the English lookup below rather than return nothing.

    # Try exact match first
    if class_name in TREATMENTS:
        return TREATMENTS[class_name]

    # Try partial match
    class_lower = class_name.lower()
    for key, treatment in TREATMENTS.items():
        if key.lower() in class_lower or class_lower in key.lower():
            return treatment

    # Default fallback
    return {
        "status":     class_name.replace("___", " — ").replace("_", " ").title(),
        "severity":   "Unknown",
        "treatment":  "Consult your local agricultural officer for diagnosis.",
        "prevention": "Monitor crops regularly and maintain good field hygiene.",
        "fertilizer": {"applicable": False, "note": "No fertilizer data available for this class."}
    }


def detect_disease(image_bytes: bytes, lang: str = "en") -> dict:
    """
    Detect crop disease from leaf image bytes.
    Returns disease name, severity, confidence, treatment and prevention,
    localized into `lang` when a translation is available (see
    get_treatment above), otherwise in English.
    """
    if disease_model is None:
        raise RuntimeError("Disease detection model not loaded")

    # Load and preprocess image
    img = Image.open(io.BytesIO(image_bytes)).convert("RGB")
    img = img.resize((IMG_SIZE, IMG_SIZE))

    img_array = np.array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    # Predict
    predictions = disease_model.predict(img_array, verbose=0)
    pred_idx    = int(np.argmax(predictions[0]))
    confidence  = float(predictions[0][pred_idx]) * 100
    class_name  = CLASS_NAMES[pred_idx]

    # Get treatment info (localized if a translation is available)
    treatment_info = get_treatment(class_name, lang=lang)

    # Top 3 predictions
    top3_idx = np.argsort(predictions[0])[::-1][:3]
    top3 = [
        {
            "class":      CLASS_NAMES[i],
            "confidence": round(float(predictions[0][i]) * 100, 2)
        }
        for i in top3_idx
    ]

    return {
        "disease":     treatment_info.get("status", class_name),
        "class_name":  class_name,
        "severity":    treatment_info.get("severity", "Unknown"),
        "confidence":  round(confidence, 2),
        "treatment":   treatment_info.get("treatment", ""),
        "prevention":  treatment_info.get("prevention", ""),
        "fertilizer":  treatment_info.get("fertilizer", {"applicable": False, "note": "No fertilizer data available."}),
        "top3":        top3,
        "is_healthy":  "healthy" in class_name.lower()
    }